repos:
      - repo: https://github.com/pycqa/isort
        rev: 5.12.0
        hooks:
              - id: isort
                # Use the config file specific to each subproject so that each
                # project can specify its own first/third-party packages.
                args: ["--config-root=python/", "--resolve-all-configs"]
                files: python/.*
                exclude: __init__.py$
                types: [text]
                types_or: [python, cython, pyi]
      - repo: https://github.com/ambv/black
        rev: 22.3.0
        hooks:
              - id: black
                files: python/.*
      - repo: https://github.com/PyCQA/flake8
        rev: 5.0.4
        hooks:
              - id: flake8
                args: ["--config=python/.flake8"]
                files: python/.*\.py$
                types: [python]
              - id: flake8
                args: ["--config=python/.flake8.cython"]
                types: [cython]
                additional_dependencies: ["flake8-force"]
      - repo: https://github.com/pre-commit/mirrors-clang-format
        rev: v11.1.0
        hooks:
              - id: clang-format
                files: \.(h|cpp)$
                types_or: [file]
                args: ['-fallback-style=none', '-style=file', '-i']


default_language_version:
      python: python3
