repos:
      - repo: https://github.com/pycqa/isort
        rev: 5.6.4
        hooks:
              - id: isort
                args: ["--settings-path=python/setup.cfg"]
                files: python/.*
                exclude: __init__.py$
                types: [text]
                types_or: [python, cython, pyi]
      - repo: https://github.com/ambv/black
        rev: 22.3.0
        hooks:
              - id: black
                files: python/.*
      - repo: https://gitlab.com/PyCQA/flake8
        rev: 3.8.3
        hooks:
              - id: flake8
                alias: flake8
                name: flake8
                args: ["--config=python/.flake8"]
                files: python/.*\.py$
                types: [cython]
              - id: flake8
                alias: flake8-cython
                name: flake8-cython
                args: ["--config=python/.flake8.cython"]
                types: [cython]
      - repo: https://github.com/pre-commit/mirrors-clang-format
        rev: v11.1.0
        hooks:
              - id: clang-format
                files: \.(h|cpp)$
                types_or: [file]
                args: ['-fallback-style=none', '-style=file', '-i']


default_language_version:
      python: python3
