# Copyright (c) 2023, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set rapids_version = environ['RAPIDS_VERSION'] %}
{% set py_version = environ['CONDA_PY'] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: ucxx
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_GENERATOR
    - PARALLEL_LEVEL
    - SCCACHE_BUCKET
    - SCCACHE_IDLE_TIMEOUT
    - SCCACHE_REGION
    - SCCACHE_S3_KEY_PREFIX=ucxx-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=ucxx-linux64 # [linux64]
    - SCCACHE_S3_USE_SSL

requirements:
  build:
    - cmake {{ cmake_version }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - sysroot_{{ target_platform }} {{ sysroot_version }}
  host:
    - python
    - pip
    - cmake>=3.20.1,!=3.23.0
    - scikit-build>=0.13.1
    - setuptools
    - cython >=0.29,<0.30
    - numpy 1.21
    - libucxx ={{ version }}
    - ucx
    - rmm ={{ rapids_version }}
  run:
    - python
    - packaging
    - libucxx {{ version }}
    - ucx
    - {{ pin_compatible('rmm', max_pin='x.x') }}
    - {{ pin_compatible('numpy') }}
    - pynvml >=11.4.1
  run_constrained:
    - cupy >=9.5.0,<12.0.0a0
    - numba >=0.56.2

test:
  imports:
    - ucxx

about:
  home: https://rapids.ai/
  license: BSD-3-Clause
  license_family: BSD
  license_file: ../../../LICENSE
  summary: UCX Python interface based the libucxx C++ implementation
