# Copyright (c) 2023, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set cuda_spec = ">=" + cuda_major ~ ",<" + (cuda_major | int + 1) ~ ".0a0" %} # i.e. >=11,<12.0a0
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: libucxx-split

source:
  git_url: ../../..

build:
  script_env:
    - PARALLEL_LEVEL
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - SCCACHE_S3_KEY_PREFIX=libucxx-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=libucxx-linux64 # [linux64]
    - SCCACHE_BUCKET
    - SCCACHE_REGION
    - SCCACHE_IDLE_TIMEOUT
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - RAPIDS_ARTIFACTS_DIR

requirements:
  build:
    - cmake {{ cmake_version }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - sysroot_{{ target_platform }} {{ sysroot_version }}
  host:
    - cudatoolkit ={{ cuda_version }}
    - ucx
    - python

outputs:
  - name: libucxx
    version: {{ version }}
    script: install_libucxx.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      run_exports:
        - {{ pin_subpackage("libucxx", max_pin="x.x") }}
    requirements:
      build:
        - cmake {{ cmake_version }}
      run:
        - cudatoolkit {{ cuda_spec }}
    test:
      commands:
        - test -f $PREFIX/lib/libucxx.so
        - test -f $PREFIX/lib/libucxx_python.so
        - test -f $PREFIX/include/ucxx/python/exception.h
        - test -f $PREFIX/include/ucxx/python/future.h
        - test -f $PREFIX/include/ucxx/python/api.h
        - test -f $PREFIX/include/ucxx/python/constructors.h
        - test -f $PREFIX/include/ucxx/python/notifier.h
        - test -f $PREFIX/include/ucxx/python/python_future.h
        - test -f $PREFIX/include/ucxx/python/worker.h
        - test -f $PREFIX/include/ucxx/utils/python.h
        - test -f $PREFIX/include/ucxx/utils/file_descriptor.h
        - test -f $PREFIX/include/ucxx/utils/sockaddr.h
        - test -f $PREFIX/include/ucxx/utils/ucx.h
        - test -f $PREFIX/include/ucxx/notifier.h
        - test -f $PREFIX/include/ucxx/address.h
        - test -f $PREFIX/include/ucxx/component.h
        - test -f $PREFIX/include/ucxx/delayed_submission.h
        - test -f $PREFIX/include/ucxx/inflight_requests.h
        - test -f $PREFIX/include/ucxx/listener.h
        - test -f $PREFIX/include/ucxx/api.h
        - test -f $PREFIX/include/ucxx/request_helper.h
        - test -f $PREFIX/include/ucxx/request_stream.h
        - test -f $PREFIX/include/ucxx/request_tag.h
        - test -f $PREFIX/include/ucxx/typedefs.h
        - test -f $PREFIX/include/ucxx/context.h
        - test -f $PREFIX/include/ucxx/endpoint.h
        - test -f $PREFIX/include/ucxx/request.h
        - test -f $PREFIX/include/ucxx/worker_progress_thread.h
        - test -f $PREFIX/include/ucxx/constructors.h
        - test -f $PREFIX/include/ucxx/request_tag_multi.h
        - test -f $PREFIX/include/ucxx/buffer.h
        - test -f $PREFIX/include/ucxx/config.h
        - test -f $PREFIX/include/ucxx/future.h
        - test -f $PREFIX/include/ucxx/header.h
        - test -f $PREFIX/include/ucxx/worker.h
        - test -f $PREFIX/include/ucxx/exception.h
        - test -f $PREFIX/include/ucxx/log.h
    about:
      home: https://rapids.ai/
      license: BSD-3-Clause
      license_family: BSD
      license_file: ../../../LICENSE
      summary: libucxx library
  - name: libucxx-examples
    version: {{ version }}
    script: install_libucxx_examples.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: {{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
    requirements:
      build:
        - cmake {{ cmake_version }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - ninja
        - sysroot_{{ target_platform }} {{ sysroot_version }}
      host:
        - {{ pin_subpackage('libucxx', exact=True) }}
      run:
        - {{ pin_subpackage('libucxx', exact=True) }}
    about:
      home: https://rapids.ai/
      license: BSD-3-Clause
      license_family: BSD
      license_file: ../../../LICENSE
      summary: libucxx examples executables
  - name: libucxx-tests
    version: {{ version }}
    script: install_libucxx_tests.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
    requirements:
      build:
        - cmake {{ cmake_version }}
      run:
        - {{ pin_subpackage('libucxx', exact=True) }}
        - cudatoolkit {{ cuda_spec }}
        - gtest {{ gtest_version }}
        - gmock {{ gtest_version }}
    about:
      home: https://rapids.ai/
      license: BSD-3-Clause
      license_family: BSD
      license_file: ../../../LICENSE
      summary: libucxx test & benchmark executables
